### PR TITLE
Some useful feature added

### PR DESCRIPTION
**Pull request by sinadalvand**
+ dot mode added to Indicator Appearance
+ font set added
+ specific width added to indicator
+ only text added to selected Tab Type

### CODE REVIEW

**Comment by Droppers** [comment]
Thank you for your pull request.

I am not sure about the TextOnly feature, it doesn't really fit in this library since it will behave like a regular bottombar (and not **Animated**BottomBar 😉). But, I think adding a dot indicator is a good addition.

Also, what is the purpose of `tabIconColorDisable`?

**Comment by sinadalvand** [comment]
> Thank you for your pull request.
> 
> I am not sure about the TextOnly feature, it doesn't really fit in this library since it will behave like a regular bottombar (and not **Animated**BottomBar 😉). But, I think adding a dot indicator is a good addition.
> 
> Also, what is the purpose of `tabIconColorDisable`?

oh , I forgot to explain that one , that's a feature to disable or enable tint that override to tabs icons , so whit this attr use can control tint enable or disable for tabs

**Comment by Droppers** [comment]
What exactly is the use-case of a feature like this? Is because you supply a tinted drawable and you don't want it to be overriden?

**Comment by sinadalvand** [comment]
> What exactly is the use-case of a feature like this? Is because you supply a tinted drawable and you don't want it to be overriden?



> What exactly is the use-case of a feature like this? Is because you supply a tinted drawable and you don't want it to be overriden?

yeah , some times people don't want apply any tint on tabs icon , but in default the "abb_tabColor"  value is "@color/textColorPrimary" and override that color in whole icon , by using "tabIconColorDisable" you can prevent change color and use the original icon colors !

**Comment by Haid-Faiz** [comment]
@sinadalvand @Droppers @rosuH

Hi, i want to use this with navController but as i am beginner in Android... so i am facing difficulties in setting it up with navController..
Could you please help me in using it with navController ?

**Pull request closed without merging**
